# Generated by Django 3.1.3 on 2020-12-07 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic',
            name='updated_at',
        ),
    ]
